In [1]:
import aqdatac
aqdatac.login('huangchunyang', password='20020308hd')

In [2]:
aqdatac.current_session()

aqdatac: version 0.2.3
current user: huangchunyang
current session expires at: 2024-07-19 14:17:09

In [3]:
import matching_orders

In [4]:
import datetime as dt

In [5]:
aqdatac.accessible_tables()

{'aindexcsi500weight': ['*'],
 'aindexhs300closeweight': ['*'],
 'aindexhs300freeweight': ['*'],
 'cftick': ['2019-01-01,2019-07-01'],
 'cfuturescalendar': ['*'],
 'chinaetfpchredmlist': ['*'],
 'chinaetfpchredmmembers': ['*'],
 'csbar_1d': ['2009-01-01, 2019-12-31'],
 'csbar_30m': ['2015-01-01, 2019-12-31'],
 'csdate': ['*'],
 'csinfo': ['*'],
 'csord': ['2019-01-01,2019-07-01'],
 'cstick': ['2019-01-01,2019-07-01'],
 'cstra': ['2019-01-01,2019-07-01']}

In [6]:
startdate = dt.date(2019, 5, 6)
enddate = dt.date(2019, 5, 7)
symlist = ["000001.SZ"]  #list
df = aqdatac.get_data("cstick",startdate, enddate, symlist)  #按日期查询指定证券

In [7]:
df

,date,time,sym,prevclose,open,high,low,close,volume,turnover,...,asize8,ask9,asize9,ask10,asize10,avgbid,avgask,totalbsize,totalasize,iopv
0,2019-05-07,09:00:45,000001.SZ,12.87,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2019-05-07,09:01:45,000001.SZ,12.87,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2019-05-07,09:02:45,000001.SZ,12.87,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2019-05-07,09:03:45,000001.SZ,12.87,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2019-05-07,09:04:45,000001.SZ,12.87,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9782,2019-05-06,15:10:03,000001.SZ,13.85,13.1,13.35,12.71,12.87,210866784.0,2742409411.07,...,573431.0,12.96,22000.0,12.97,17600.0,12.66,13.8,8781562.0,11629483.0,0.0
9783,2019-05-06,15:11:03,000001.SZ,13.85,13.1,13.35,12.71,12.87,210866784.0,2742409411.07,...,573431.0,12.96,22000.0,12.97,17600.0,12.66,13.8,8781562.0,11629483.0,0.0
9784,2019-05-06,15:12:03,000001.SZ,13.85,13.1,13.35,12.71,12.87,210866784.0,2742409411.07,...,573431.0,12.96,22000.0,12.97,17600.0,12.66,13.8,8781562.0,11629483.0,0.0
9785,2019-05-06,15:13:03,000001.SZ,13.85,13.1,13.35,12.71,12.87,210866784.0,2742409411.07,...,573431.0,12.96,22000.0,12.97,17600.0,12.66,13.8,8781562.0,11629483.0,0.0
9786,2019-05-06,15:14:03,000001.SZ,13.85,13.1,13.35,12.71,12.87,210866784.0,2742409411.07,...,573431.0,12.96,22000.0,12.97,17600.0,12.66,13.8,8781562.0,11629483.0,0.0